//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB.DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spaces
    {
        public long ID { get; set; }
        public System.DateTime timestamp { get; set; }
        public string andar { get; set; }
        public long vagas_totais { get; set; }
        public long vagas_disponiveis { get; set; }
        public long vagas_ocupadas { get; set; }
    }
}
